export const FAQS = [
  { q: "How much does detailing cost?",
    a: "It depends on the package and how dirty the car is. Most jobs start at $79 and go up from there. You can see exact pricing per vehicle type on each service page." },
  { q: "Do you come to me?",
    a: "Yes — everything is mobile. We come to your house or your work. All we need is access to a parking spot." },
  { q: "How long does it take?",
    a: "Usually between 1.5 and 4 hours depending on the package and how dirty the vehicle is. Maintenance details are faster." },
  { q: "How often should I get my car detailed?",
    a: "Most people do a full detail every few months, or stay on a maintenance plan with regular Express Cleans in between." },
  { q: "Do you work evenings and weekends?",
    a: "Yes — that's when most bookings happen. We're open Monday, Tuesday, and Friday from 4 PM to 10 PM, and Saturday and Sunday from 9 AM to 10 PM." },
  { q: "What areas do you service?",
    a: "Port Coquitlam and Coquitlam right now. We're expanding across the Lower Mainland — submit the booking form and we'll add you to the waitlist if you're outside the current service area." },
  { q: "Do I need to be home during the detail?",
    a: "Not necessarily. As long as we have access to your vehicle and a power outlet (we'll let you know in advance if needed), you can leave us to it." },
  { q: "What payment methods do you accept?",
    a: "Payment is taken in person on the day of service. We'll confirm accepted methods when we reply to your booking request." },
  { q: "How far in advance should I book?",
    a: "We require at least 24 hours notice. Weekends fill up fastest, so booking 3–7 days ahead is recommended for Saturdays and Sundays." },
  { q: "Can you remove pet hair and odors?",
    a: "Yes. Pet Hair Removal and Odor Removal are available as add-ons, or built into our Premium Detail." },
] as const;
